spring:
  application:
    name: ${APP_NAME:inquiry}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD:mongodb}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB:supportdb}?authSource=admin

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    com.telecom: DEBUG

